version: "3.7"

services:
  pebble:
    build: docker/pebble
    healthcheck:
      test: ["CMD", "/check.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      - PEBBLE_VA_ALWAYS_VALID=true
    command: pebble -config /test/config/pebble-config.json -strict -dnsserver 10.30.50.3:8053
    networks:
      acmenet:
        ipv4_address: 10.30.50.2
    depends_on:
      - challtestsrv
  challtestsrv:
    image: letsencrypt/pebble-challtestsrv:latest
    command: pebble-challtestsrv -defaultIPv6 "" -defaultIPv4 10.30.50.3
    networks:
      acmenet:
        ipv4_address: 10.30.50.3
  dev_clickhouse_server:
    image: clickhouse/clickhouse-server:23.6.2.18-alpine
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - ./_dev/clickhouse:/var/lib/clickhouse
      - ./_dev/clickhouse-users/:/etc/clickhouse-server/users.d/
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      acmenet:
        ipv4_address: 10.30.50.4
  integration_server:
    build: .
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8087/health || exit 1
      interval: 30s
      retries: 3
      start_period: 3s
      timeout: 10s
    environment:
      - BRUM_SERVER_PORT=8087
      - BRUM_DATABASE_HOST=dev_clickhouse_server
      - BRUM_DATABASE_PORT=9000
      - BRUM_DATABASE_NAME=default
      - BRUM_DATABASE_USERNAME=default
      - BRUM_DATABASE_PASSWORD=
      - BRUM_DATABASE_TABLE_PREFIX=integration_test_
      - BRUM_PERSISTANCE_DATABASE_STRATEGY=all_in_one_db
      - BRUM_PERSISTANCE_TABLE_STRATEGY=all_in_one_table
      - BRUM_BACKUP_ENABLED=false
      - BRUM_BACKUP_DIRECTORY=/home/basicrum_archive
      - BRUM_BACKUP_EXPIRED_DIRECTORY=/home/basicrum_expired
      - BRUM_BACKUP_UNKNOWN_DIRECTORY=/home/basicrum_unknown
      - BRUM_BACKUP_INTERVAL_SECONDS=5
      - BRUM_SERVER_SSL=true
      - BRUM_SERVER_SSL_TYPE=LETS_ENCRYPT
      - BRUM_SERVER_SSL_LETS_ENCRYPT_DOMAIN=your-domain.com
      - BRUM_CHECK_SUBSCRIPTION=false
      - TEST_DIRECTORY_URL=https://10.30.50.2:14000/dir
      - TEST_INSECURE_SKIP_VERIFYy=true
    depends_on:
      dev_clickhouse_server:
        condition: service_healthy
      pebble:
        condition: service_healthy
    networks:
      acmenet:
        ipv4_address: 10.30.50.5
  integration_test:
    image: golang:1.19-alpine
    environment:
      - CGO_ENABLED=0
      - DOMAIN=your-domain.com
      - DOMAIN_IP=10.30.50.5
    working_dir: /go/src/app/
    command: go run cmd/testletsencrypt/main.go
    volumes:
      - .:/go/src/app/
    depends_on:
      integration_server:
        condition: service_healthy
    networks:
      acmenet:
        ipv4_address: 10.30.50.6

networks:
  acmenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.50.0/24
