version: "3.7"

services:
  dev_clickhouse_server2:
    image: clickhouse/clickhouse-server:23.6.2.18-alpine
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - 8143:8123
      - 9000:9000
    volumes:
      - ./_dev/clickhouse2:/var/lib/clickhouse2
      - ./_dev/clickhouse-users/:/etc/clickhouse-server/users.d/
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  integration_server2:
    build: .
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8087/health || exit 1
      interval: 30s
      retries: 3
      start_period: 3s
      timeout: 10s
    environment:
      - BRUM_SERVER_PORT=8087
      - BRUM_DATABASE_HOST=dev_clickhouse_server2
      - BRUM_DATABASE_PORT=9000
      - BRUM_DATABASE_NAME=default
      - BRUM_DATABASE_USERNAME=default
      - BRUM_DATABASE_PASSWORD=
      - BRUM_DATABASE_TABLE_PREFIX=
      - BRUM_PERSISTANCE_DATABASE_STRATEGY=all_in_one_db
      - BRUM_PERSISTANCE_TABLE_STRATEGY=all_in_one_table
      - BRUM_BACKUP_ENABLED=false
      - BRUM_BACKUP_DIRECTORY=/home/basicrum_archive
      - BRUM_BACKUP_EXPIRED_DIRECTORY=/home/basicrum_expired \
	    - BRUM_BACKUP_UNKNOWN_DIRECTORY=/home/basicrum_unknown \
      - BRUM_BACKUP_INTERVAL_SECONDS=5
    depends_on:
      dev_clickhouse_server2:
        condition: service_healthy
  integration_test2:
    image: golang:1.21-alpine
    environment:
      - BRUM_SERVER_HOST=integration_server2
      - BRUM_SERVER_PORT=8087
      - BRUM_DATABASE_HOST=dev_clickhouse_server2
      - BRUM_DATABASE_PORT=9000
      - BRUM_DATABASE_NAME=default
      - BRUM_DATABASE_USERNAME=default
      - BRUM_DATABASE_PASSWORD=
      - BRUM_DATABASE_TABLE_PREFIX=
      - CGO_ENABLED=0
    depends_on:
      integration_server2:
        condition: service_healthy
    working_dir: /go/src/app/it
    command: go test
    volumes:
      - .:/go/src/app/
  unit_test:
    image: golang:1.21-alpine
    environment:
      - CGO_ENABLED=0
    working_dir: /go/src/app/beacon
    command: go test
    volumes:
      - .:/go/src/app/
