version: "3.7"

services:
  dev_clickhouse_server:
    image: clickhouse/clickhouse-server:22.8
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 5s
      retries: 3    
    ports:
      - 8143:8123
      - 9000:9000
    volumes:
      - ./_dev/clickhouse:/var/lib/clickhouse
      - ./_dev/clickhouse-users/:/etc/clickhouse-server/users.d/
    ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
  integration_server:
    build: .
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8087/health || exit 1
      interval: 30s
      retries: 3
      start_period: 3s
      timeout: 10s
    environment:
      - SERVER_HOST=localhost
      - SERVER_PORT=8087
      - DATABASE_HOST=dev_clickhouse_server
      - DATABASE_PORT=9000
      - DATABASE_NAME=default
      - DATABASE_USERNAME=default
      - DATABASE_PASSWORD=
      - DATABASE_TABLE_PREFIX=
      - PERSISTANCE_DATABASE_STRATEGY=all_in_one_db
      - PERSISTANCE_TABLE_STRATEGY=all_in_one_table
      - BACKUP_ENABLED=false
      - BACKUP_DIRECTORY=/home/basicrum_archive
      - BACKUP_INTERVAL_SECONDS=5
    depends_on:
      dev_clickhouse_server:
        condition: service_healthy
  integration_test:
    image: golang:1.19
    environment:
      - SERVER_HOST=integration_server
      - SERVER_PORT=8087
      - DATABASE_HOST=dev_clickhouse_server
      - DATABASE_PORT=9000
      - DATABASE_NAME=default
      - DATABASE_USERNAME=default
      - DATABASE_PASSWORD=
      - DATABASE_TABLE_PREFIX=
    depends_on:
      integration_server:
        condition: service_healthy
    working_dir: /go/src/app/it
    command: go test
    volumes:
      - .:/go/src/app/      
  unit_test:
    image: golang:1.19
    working_dir: /go/src/app/beacon
    command: go test
    volumes:
      - .:/go/src/app/

