# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    branches: ["!*"]
    tags: ["*"]
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Unit Test
      working-directory: /home/runner/work/front_basicrum_go/front_basicrum_go
      run: make docker-unit-test

    - name: Integration test
      working-directory: /home/runner/work/front_basicrum_go/front_basicrum_go
      run: make docker-integration-test

    - name: Integration test without table prefix
      working-directory: /home/runner/work/front_basicrum_go/front_basicrum_go
      run: make docker-integration-test-noprefix

    - name: Integration test letsencrypt
      working-directory: /home/runner/work/front_basicrum_go/front_basicrum_go
      run: make docker-integration-test-letsencrypt
